### ISSUE TITLE
Test 1: Raise Alarm

### ISSUE THREAD

**Issue by som98** [som98/Forestalling-of-Fishes_DESIGN-LAB-IEM#1]
If the water level is negative(<0) then net was being lowered.

**Comment by som98** [comment]
In release 0.2 the issue regarding the negative value of water level was resolved,

**Comment by som98** [comment]
The issue was resolved.

**Comment by Yajushid** [comment]
> The issue was resolved.

#change

**Comment by Yajushid** [comment]
Only change made was in the function in sensor.py file :
def raise_alarm(self, id, waterlevel, threshold):
        filename = "raise_alarm_"+id
        alarm1 = open(filename, "w")
        alarm =''
        if (waterlevel > threshold):
            alarm='1'
        elif (waterlevel < 0):
            alarm="error"
        elif (waterlevel <= threshold):
            alarm ='0'
        alarm1.write(alarm)
        return alarm

**Comment by Yajushid** [comment]
Since practically water level cannot be negative, I have added an elif condition to check for waterlevel less than 0. If that condition gets satisfied we write an error to the file. The rest of the code remains same.
