### ISSUE TITLE
Improvements for Release 0.2

### ISSUE THREAD

**Issue by som98** [som98/Forestalling-of-Fishes_DESIGN-LAB-IEM#3]
- Shouldn't have 2 different files for sensor and sensor manager.

- Should have a fixed lookuptable for mac addresses and shouldn't be entered by user every time.

- Should store water level and mac as separate files for separate sensors.

**Comment by shyanka21** [comment]
xyz

**Comment by shyanka21** [comment]
We now have just one sensor module which will run as separate processes. 
For the Mac addresses we have created a predefined look up table.
[sensor_module.txt](https://github.com/som98/Forestalling-of-Fishes_DESIGN-LAB-IEM/files/4804145/sensor_module.txt)

**Comment by som98** [comment]
[sensor_module.py](url)

**Comment by som98** [comment]
Fixed and verified.
